
package tech.dev.web.jaxws.seitest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebServ", targetNamespace = "http://jaxws.test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebServ {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfo", targetNamespace = "http://jaxws.test.com/", className = "com.test.jaxws.GetInfo")
    @ResponseWrapper(localName = "getInfoResponse", targetNamespace = "http://jaxws.test.com/", className = "com.test.jaxws.GetInfoResponse")
    @Action(input = "http://jaxws.test.com/TestWebServ/getInfoRequest", output = "http://jaxws.test.com/TestWebServ/getInfoResponse")
    public String getInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
