
package tech.dev.web.jaxws.sei;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientWebServ", targetNamespace = "http://jaxws.clients.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientWebServ {


    /**
     * 
     * @return
     *     returns java.util.List<com.clients.jaxws.ClientTO>
     */
    @WebMethod(action = "fetch_clients")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchClients", targetNamespace = "http://jaxws.clients.com/", className = "com.clients.jaxws.FetchClients")
    @ResponseWrapper(localName = "fetchClientsResponse", targetNamespace = "http://jaxws.clients.com/", className = "com.clients.jaxws.FetchClientsResponse")
    @Action(input = "fetch_clients", output = "http://jaxws.clients.com/ClientWebServ/fetchClientsResponse")
    public List<ClientTO> fetchClients();

}
