
package tech.dev.web.jaxws.sei;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientWebService", targetNamespace = "http://jaxws.clients.com/", wsdlLocation = "http://localhost:1234/crm/jaxws/ClientWebService?wsdl")
public class ClientWebService
    extends Service
{

    private final static URL CLIENTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTWEBSERVICE_EXCEPTION;
    private final static QName CLIENTWEBSERVICE_QNAME = new QName("http://jaxws.clients.com/", "ClientWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/crm/jaxws/ClientWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTWEBSERVICE_WSDL_LOCATION = url;
        CLIENTWEBSERVICE_EXCEPTION = e;
    }

    public ClientWebService() {
        super(__getWsdlLocation(), CLIENTWEBSERVICE_QNAME);
    }

    public ClientWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTWEBSERVICE_QNAME, features);
    }

    public ClientWebService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTWEBSERVICE_QNAME);
    }

    public ClientWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTWEBSERVICE_QNAME, features);
    }

    public ClientWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientWebServ
     */
    @WebEndpoint(name = "ClientWebServicePort")
    public ClientWebServ getClientWebServicePort() {
        return super.getPort(new QName("http://jaxws.clients.com/", "ClientWebServicePort"), ClientWebServ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientWebServ
     */
    @WebEndpoint(name = "ClientWebServicePort")
    public ClientWebServ getClientWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxws.clients.com/", "ClientWebServicePort"), ClientWebServ.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTWEBSERVICE_EXCEPTION!= null) {
            throw CLIENTWEBSERVICE_EXCEPTION;
        }
        return CLIENTWEBSERVICE_WSDL_LOCATION;
    }

}
